baseURL = "https://jetjaguar-psx.github.io/"
languageCode = "ja-JP"
title = " T.Tanaka's notes"
theme = "github-style"

[params]
  author = "T.Tanaka"
  description = "島根大学ものづくり部Pim"
  url = "https://jetjaguar-psx.github.io/"
  keywords = "自作キーボード設計, Unity, 空間オーディオ, ものづくり"
  favicon = "/images/shiitake.png"
  location = "Japan"
  enableGitalk = false


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
